apiVersion: v1
kind: List
items:
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: openshift-tasks-cicd
    creationTimestam: null
  displayName: Openshift Tasks App - CI/CD
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: openshift-tasks-dev
    creationTimestam: null
  displayName: Openshift Tasks App - Dev
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: openshift-tasks-stage
    creationTimestam: null
  displayName: Openshift Tasks App - Stage
- kind: ProjectRequest
  apiVersion: v1
  metadata:
    name: openshift-tasks-prod
    creationTimestam: null
  displayName: Openshift Tasks App - Prod
