---
- name: Check Docker
  hosts: nodes
  
  tasks:
    - name: Check - docker running
      shell: systemctl status docker | grep Active
    
    - name: Check - docker version
      shell: docker version|grep Version

- name: Check repos
  hosts: all

  tasks:
    - name: Check - repos
      yum:
        list: repolist      
      register: result

- name: Check NFS
  hosts: nfs

  tasks:
    - name: Check - NFS
      shell: exportfs


#- name: Include the prerequisites playbook
#  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/prerequisites.yml
#  when: openshift_install
#  vars:
#    openshift_install: false

#- name: Include the deploy_cluster playbook
#  import_playbook: /usr/share/ansible/openshift-ansible/playbooks/deploy_cluster.yml
#  when: openshift_install
#  vars:
#    openshift_install: false

