---
- name: Check Docker
  hosts: nodes
  
  tasks:
    - name: Check - docker running
      shell: systemctl status docker | grep Active
    
    - name: Check - docker version
      shell: docker version|grep Version

- name: Check repos
  hosts: all

  tasks:
    - name: Check - repos
      yum:
        list: repolist      
      register: result

- name: Check NFS
  hosts: nfs

  tasks:
    - name: Check - NFS
      shell: exportfs

