---
- name: Automatize all the tasks
  hosts: localhost 
  vars:
    version: 1
    guid: ea11
    repo: https://github.com/alvarolop/ocp-deployment-homework
    server_domain: a

  tasks:
    - name: Replace values of the GUID in the openshift-ansible hosts file
      replace:
        path: ./hosts-template-alvaro-v1
        regexp: '<GUID>'
        replace: '{{ guid }}' 
#        backup: yes
    
