apiVersion: v1
items:
- kind: "BuildConfig"
  apiVersion: "v1"
  metadata:
    name: "cicd-bc"
  spec:
#    triggers:
#          - github:
#              secret: 5Mlic4Le
#            type: GitHub
#          - generic:
#              secret: FiArdDBH
#            type: Generic
    strategy:
      type: "JenkinsPipeline"
      jenkinsPipelineStrategy:
        jenkinsfilePath: Jenkinsfile
    source:
      git:
        ref: eap-7
        uri: https://github.com/alvarolop/openshift-tasks
      type: Git

kind: List
metadata: {}
