---
- name: Automatize all the tasks
  hosts: localhost 
  connection: local
  tasks:
    - name: Create a var with the GUID value
      shell: hostname | cut -d"." -f2
      register: guid 

    - name: Replace values of the GUID in the openshift-ansible hosts file
      replace:
        path: ../hosts
        regexp: '<GUID>'
        replace: '{{ guid.stdout }}' 

    - name: Refresh inventory to ensure new instaces exist in inventory
      meta: refresh_inventory

    - name: Install tools
      yum:
        name: "{{ packages }}"
      vars:
        packages:
        - atomic-openshift-utils
        - atomic-openshift-clients

- name: Check Docker
  hosts: nodes
  tasks:
    - name: Check - docker running
      command: systemctl status docker | grep Active

    - name: Check - docker version
      command: docker version | grep Version

- name: Check repos
  hosts: all
  tasks:
    - name: Check - repos
      yum:
        list: repolist
      register: result

- name: Check NFS
  hosts: nfs
  tasks:
    - name: Check - NFS
      command: exportfs

