---

- name: Check Docker
  hosts: nodes
  tasks:
    - name: Check - docker running
      command: systemctl status docker | grep Active

    - name: Check - docker version
      command: docker version | grep Version

- name: Check repos
  hosts: all
  tasks:
    - name: Check - repos
      yum:
        list: repolist
      register: result

- name: Check NFS
  hosts: nfs
  tasks:
    - name: Check - NFS
      command: exportfs

