---
- name: Check Docker
  hosts: nodes
  tasks:
    - name: Check - docker running
      service:
        name: docker
        statue: started

- name: Check repos
  hosts: all
  tasks:
    - name: Check - repos
      yum:
        list: repolist
      register: result

- name: Check NFS
  hosts: nfs
  tasks:
    - name: Check - NFS
      command: exportfs

