---
- name: Copy the system:admin certificate in the bastion 
  hosts: masters[0]
  vars:
    version: 1
  tasks:
    - name:  
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes

