---
- name: Copy the system:admin certificate in the bastion 
  hosts: masters[0]
  vars:
    version: 1
  tasks:
    - name: Copy files
      fetch:
        src: /root/.kube/config
        dest: /root/.kube/config
        flat: yes
- name: Check installation
  hosts: masters
  tasks:
    - name: Check etcd instances
      command: "systemctl status etcd"

- name: Create the new network policy
  hosts: localhost
  tasks:
    - name: Load project template
      command: oc create -f ../templates/project_template.yaml

- name: Tell openshift to use the new template
  hosts: masters
  tasks:
    - name: Add the new project template
      replace:
        path: /etc/origin/master/master-config.yaml
        regexp: "  projectRequestTemplate: ''"
        replace:  "  projectRequestTemplate: 'default/project-request'"

# Generate default project template
# https://docs.openshift.com/container-platform/3.9/admin_guide/managing_projects.html#modifying-the-template-for-new-projects
# 1. oc adm create-bootstrap-project-template -o yaml > template.yaml
# 2. Modify it
# 3. oc create -f template.yaml -n default
# 4. Notify the masters that they have to use the new project template
