---
- name: CICD Workflow
  hosts: localhost
  connection: local
  tasks:
    - name: Login as system:admin
      command: "oc login -u system:admin"

    - name: Create the openshift projects
      command: "oc new-project {{ item }}"
      with_items:
        - "cicd --description='CI/CD Tools Environment' --display-name='CICD - Jenkins'"
        - "tasks-project --description='Openshift tasks Environment' --display-name='Openshift Tasks'"
 
    - name: Deploy Jenkins pipeline
      command: "oc new-app jenkins-persistent -n cicd"

    - name: Add policy to the jenkins role of cicd to allow it to access the tasks-project
      command: "oc policy add-role-to-user edit system:serviceaccount:cicd:jenkins -n tasks-project"

#    - name: Add policy to all the service account groups in the tasks-project to pull images
#      command: "oc adm policy add-role-to-group system:image-puller system:serviceaccounts:tasks-project -n cicd"

#    - name: Wait
#      command: sleep 20

    - name: Create Jenkins Pipeline
      command: "oc create -f ../templates/jenkins_build_config.yaml -n cicd"
